### ISSUE TITLE
Chat Summarize Not Returning Information from Notes

### ISSUE THREAD

**Issue by Velora** [debanjum/khoj#137]
Hello, great work on this! 

## **Use:**
I'm using the Obsidian plugin and the search works excellently. I'd like to also use the web interface ie: http://localhost:8000/chat?type=summarize to chat about my notes from Obsidian. 

I have followed the steps to configure the chat by editing khoj.yml with the following under `processor:`

```
  conversation:
    conversation-logfile: /Users/name/.khoj/processor/conversation/conversation_logs.json
    model: text-davinci-003
    openai-api-key: sk-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

I can verify that requests are being sent to OpenAI when I use the chat web interface, and I have restarted khoj and updated the index before chatting.

## **Expectation:**
I expected that when I typed chat queries about my notes, that I would receive a contextual response using data from my notes in Obsidian. I used the "summarize" type in chat. 

## **Result:**
The chat responded with information that had no context about my notes, despite trying many ways of phrasing questions. Is the summarize type prone to hallucination, or is it supposed to specifically use the context of embedded documents?
