### ISSUE TITLE
Recursively search folders

### ISSUE THREAD

**Issue by vadi2** [debanjum/khoj#208]
Thanks for the tool! It would be great if khoj could recursively search folders when you're setting it up, instead of needing to be pointed to every file individually.

**Comment by debanjum** [comment]
Hey @vadi2, are you using Khoj from Emacs or Obsidian?

To specify a (set of folders) to index, you can manually set the `input-filter` field to list of glob style file paths instead of the `input-files` field in your khoj configuration file at ~/khoj/khoj.yml. 

An snipped example khoj config for reference:
```yaml
content-type:
  markdown:
    input-files: null
    input-filter: 
    - /path/to/first/folder/**/*.md
    - /path/to/second/folder/**/*.md
```

Let me know if that doesn't suffice for your use-case
