### ISSUE TITLE
Error when switching to open AI embeddings

### ISSUE THREAD

**Issue by rmulligan** [debanjum/khoj#216]
**Config:** 
```
processor:
  conversation:
    conversation-logfile: ~/.khoj/processor/conversation/conversation.json
    model: "text-davinci-003"
    openai-api-key: omitted
search-type:
  asymmetric:
    encoder: text-embedding-ada-002
    encoder-type: khoj.utils.models.OpenAI
    cross-encoder: cross-encoder/ms-marco-MiniLM-L-6-v2
    model-directory: null
  image:
    encoder: sentence-transformers/clip-ViT-B-32
    encoder-type: null
    model-directory: ~/.khoj/search/image
  symmetric:
    cross-encoder: cross-encoder/ms-marco-MiniLM-L-6-v2
    encoder: sentence-transformers/all-MiniLM-L6-v2
    encoder-type: null
    model-directory: ~/.khoj/search/symmetric
```

Error:

  File "/Users/ryanmulligan/.pyenv/versions/3.10.11/bin/khoj", line 8, in <module>
    sys.exit(run())
  File "/Users/ryanmulligan/.pyenv/versions/3.10.11/lib/python3.10/site-packages/khoj/main.py", line 88, in run
    configure_server(args, required=False)
  File "/Users/ryanmulligan/.pyenv/versions/3.10.11/lib/python3.10/site-packages/khoj/configure.py", line 49, in configure_server
    state.model = configure_search(state.model, state.config, args.regenerate)
  File "/Users/ryanmulligan/.pyenv/versions/3.10.11/lib/python3.10/site-packages/khoj/configure.py", line 90, in configure_search
    model.orgmode_search = text_search.setup(
  File "/Users/ryanmulligan/.pyenv/versions/3.10.11/lib/python3.10/site-packages/khoj/search_type/text_search.py", line 173, in setup
    bi_encoder, cross_encoder, top_k = initialize_model(search_config)
  File "/Users/ryanmulligan/.pyenv/versions/3.10.11/lib/python3.10/site-packages/khoj/search_type/text_search.py", line 40, in initialize_model
    bi_encoder = load_model(
  File "/Users/ryanmulligan/.pyenv/versions/3.10.11/lib/python3.10/site-packages/khoj/utils/helpers.py", line 72, in load_model
    model = model_type_class(model_name, device=device)
  File "/Users/ryanmulligan/.pyenv/versions/3.10.11/lib/python3.10/site-packages/khoj/utils/models.py", line 33, in __init__
    f"Set OpenAI API key under processor-config > conversation > openai-api-key in config file: {config_file}"
Exception: Set OpenAI API key under processor-config > conversation > openai-api-key in config file: None
