### ISSUE TITLE
Support Multiple Input Filters

### ISSUE THREAD

**Issue by debanjum** [debanjum/khoj#84]
`input-filter` field in `khoj.yml` only accepts a single glob string currently. Allow passing a list of glob strings to `input-filter` for filtering

Current:
```yml
content-type:
  org: 
    input-filter: "~/notes/*.org"
```
Expected:
```yml
content-type:
  org: 
    input-filter: 
      - "~/notes/*.org"
      - "~/documents/*.org"
```
