### ISSUE TITLE
Searching words in arbitrary order (aka helm)

### ISSUE THREAD

**Issue by yantar92** [debanjum/khoj#88]
I have the following headline:

```org
******** DONE Zheng, Mara [Nature Communications] (2013) High-strength and thermally stable bulk nanolayered composites due to twin-induced interfaces :BOOKMARK:FLAGGED:@work:article:ATTACH:
CLOSED: [2022-07-20 Wed 09:58]
:PROPERTIES:
:CREATED: [2020-05-21 Thu 12:12]
:Source: https://www.nature.com/articles/ncomms2651
:ID:       Zheng_2013
:PUBLISHER: Nature Publishing Group
:NOTE:     Online; accessed 14 August 2021
:HOWPUBLISHED: Nature
:URL:      https://doi.org/10.1038/ncomms2651
:DOI:      10.1038/ncomms2651
:YEAR:     2013
:JOURNAL:  Nature Communications
:AUTHOR:   Zheng, Shijian and Beyerlein, Irene J. and Carpenter, John S. and Kang, Keonwook and Wang, Jian and Han, Weizhong and Mara, Nathan A.
:BTYPE:    article
:TITLE:    High-strength and thermally stable bulk nanolayered composites due to twin-induced interfaces
:Effort:   0:20
:SHOWFROMDATE: 2021-09-04
:END:
:LOGBOOK:
- State "DONE"       from "REVIEW"          [2022-07-20 Wed 09:58]
- State "DONE"       from "DONE"          [2021-09-06 Mon 13:57]
CLOCK: [2021-09-06 Mon 13:48]--[2021-09-06 Mon 13:57] =>  0:09
CLOCK: [2021-09-03 Fri 14:20]--[2021-09-03 Fri 14:43] =>  0:23
CLOCK: [2021-09-02 Thu 13:59]--[2021-09-02 Thu 14:06] =>  0:07
CLOCK: [2021-08-31 Tue 15:14]--[2021-08-31 Tue 15:17] =>  0:03
CLOCK: [2021-08-30 Mon 16:04]--[2021-08-30 Mon 16:09] =>  0:05
CLOCK: [2021-08-27 Fri 17:22]--[2021-08-27 Fri 17:29] =>  0:07
- Refiled on [2021-08-14 Sat 11:52]
- Refiled on [2021-03-19 Fri 16:01]
- Refiled on [2020-08-18 Tue 17:39]
- Refiled on [2020-05-22 Fri 10:24]
:END:
 #ARB #EBSD #Cu-Nb #texture

- Cu/Nb ARB texture evolves like the following:
  - Nb={112}<110> all the time (<100nm layer thickness); Cu={4 4 11}<11 11 8> (200-100nm) -> {112}<111> (100-50nm) -> {112}<111> + twin {552}<115> (50-10nm) -> {552}<115> -> {551}<1 1 10> (10nm)
- Layers are single crystalline (SX) below 200nm layer thickness
```

I am trying to match it using "thermally stable high strength" search term. However, no match is given, which is unexpected.

**Comment by debanjum** [comment]
By no match is given, do you mean no results are returned for the above query at all or that the entry you shared doesn't match?
1. No results at all is unexpected as `khoj` by default does a best effort match so it should return some results (unless you use the word/file/date `filters`)
2. If the issue is that the above entry isn't returned, I'd suspect that's because the property drawer (is currently) ignored during indexing and most of the relevant keywords in the entry seem to be in the property drawer

**Comment by yantar92** [comment]
1. Some other results are given on my side, but not the entry
2. All the keywords in the search term are from the headline itself, not from the drawer.

**Comment by debanjum** [comment]
> 2. All the keywords in the search term are from the headline itself, not from the drawer

Ah, missed that 🙈. Yeah, that does seem unexpected (assuming you don't have other more relevant entries in your files). Let me check if the entry is getting parsed, indexed as expected on my end.

But just to clarify, searching for words in arbitrary order with `khoj` *should be* perfectly fine. The semantic meaning of the query sentence is what the model cares more about, rather than specific word order

**Comment by debanjum** [comment]
1. Don't see any issue in parsing, indexing the entry
2. Running the exact query you mentioned above (when the entry is indexed alongside all my other notes) returns the entry as the third result for me *before re-ranking* and the first result *after re-ranking* by the cross-encoder for me
   - Re-ranking improves the quality of the search results at the cost of higher search latency
   - You can trigger re-ranking from within Emacs by running `C-c RET` from the `khoj` query minibuffer. So `M-x khoj <query> C-c RET`. (On the web interface, hitting enter will re-rank the results)

**Comment by yantar92** [comment]
1. I tried re-ranking. The heading in question is still missing
2. This is actually natural language. Just technical. I also tried "thermally stable strength" - no luck.
3. What are filters? Search terms? Are they documented?

I am also attaching the actual results for reference.
[Khoj.tar.gz](https://github.com/debanjum/khoj/files/9542275/Khoj.tar.gz)

**Comment by yantar92** [comment]
Now, I feel that I really misunderstand something about search.
I am attaching a comparison of the results when searching "Bastien" with khoj vs. org-ql.
Khoj is only giving a single(!) match, while the actual number of matching headlines is large.
![org-ql-bastien](https://user-images.githubusercontent.com/10819266/189535302-b8f3f242-f27d-4c2c-97bb-c3ba696728a0.png)
![khoj-bastien](https://user-images.githubusercontent.com/10819266/189535304-0a00812a-22a0-4111-a8a8-fea4bf8b0615.png)

My khoj config is 

```
content-type:
  org:
    index_heading_entries: true
    compressed-jsonl: ~/.khoj/content/org/org.jsonl.gz
    embeddings-file: ~/.khoj/content/org/org_embeddings.pt
    input-files:
    - /home/yantar92/Org/contacts.org
    - /home/yantar92/Org/contacts_archive_2021.org
    - /home/yantar92/Org/inbox.org
    - /home/yantar92/Org/inbox_archive_2021.org
    - /home/yantar92/Org/inbox_archive_2022.org
    - /home/yantar92/Org/Journal.org
    - /home/yantar92/Org/nodeadline_archive_2019.org
    - /home/yantar92/Org/nodeadline_archive_2020.org
    - /home/yantar92/Org/nodeadline_archive_2021.org
    - /home/yantar92/Org/notes.org
    - /home/yantar92/Org/notes.org_archive_2022.org
    - /home/yantar92/Org/notes_archive_2018.org
    - /home/yantar92/Org/notes_archive_2019.org
    - /home/yantar92/Org/notes_archive_2020.org
    - /home/yantar92/Org/notes_archive_2021.org
    - /home/yantar92/Org/notes_archive_2022.org
    - /home/yantar92/Org/References_archive_2020.org
    - /home/yantar92/Org/References_archive_2021.org
    - /home/yantar92/Org/rss.org
    - /home/yantar92/Org/rss_archive_2019.org
    - /home/yantar92/Org/rss_archive_2020.org
    - /home/yantar92/Org/rss_archive_2021.org
    - /home/yantar92/Org/rss_archive_2022.org
    - /home/yantar92/Org/schedule-work.org
    - /home/yantar92/Org/schedule-work_archive_2017.org
    - /home/yantar92/Org/schedule-work_archive_2018.org
    - /home/yantar92/Org/schedule.org
    - /home/yantar92/Org/schedule_archive_2017.org
    - /home/yantar92/Org/schedule_archive_2018.org
    - /home/yantar92/Org/schedule_archive_2019.org
    - /home/yantar92/Org/schedule_archive_2020.org
    - /home/yantar92/Org/system-config.org
    - /home/yantar92/Org/system-config_archive_2020.org
    - /home/yantar92/Org/system-config_archive_2021.org
    - /home/yantar92/Org/TODO.org
    - /home/yantar92/Org/TODO_archive_2015-2016.org
    - /home/yantar92/Org/TODO_archive_2017.org
    - /home/yantar92/Org/TODO_archive_2018.org
    - /home/yantar92/Org/TODO_archive_2019.org
    - /home/yantar92/Org/TODO_archive_2020.org
    - /home/yantar92/Org/TODO_archive_2021.org
    - /home/yantar92/Org/TODO_archive_2022.org
    - /home/yantar92/Org/zettels.org
    input-filter: null
processor: {}
search-type:
  asymmetric:
    cross-encoder: cross-encoder/ms-marco-MiniLM-L-6-v2
    encoder: sentence-transformers/multi-qa-MiniLM-L6-cos-v1
    model_directory: ~/.khoj/search/asymmetric/
  image:
    encoder: sentence-transformers/clip-ViT-B-32
    model_directory: ~/.khoj/search/image/
  symmetric:
    cross-encoder: cross-encoder/ms-marco-MiniLM-L-6-v2
    encoder: sentence-transformers/all-MiniLM-L6-v2
    model_directory: ~/.khoj/search/symmetric/

```
